AWSTemplateFormatVersion: 2010-09-09
Parameters:

#task definition
  ProductName:
   Type: String
   Description: Product Name
   Default: pmd

  AppName:
   Type: String
   Description: App Name
   Default: partmaster
  
  Environment:
   Type: String
   Description: Env Name
   Default: devl

  ContainerDefinitionsMountPointsContainerPath:
    Type: String
    Description: The path on the container to mount the host volume at.
  ContainerDefinitionsMountPointsSourceVolume:
    Type: String
    Description: The name of the volume to mount

  ContainerDefinitionsImage:
    Type: String
    Description: The image used to start a container
    Default: "847370586410.dkr.ecr.us-west-2.amazonaws.com/appmod:yellow"

  LogConfigurationLogDriver:
    Type: String
    Description: The log driver to use for the container.  
    Default: awslogs

  awslogsregion:
    Type: String
    Description: The log configuration specification for the container
    Default: "us-west-2"

  TaskdefContainerName:
    Type: String
    Description: Name of the container mentioned in task definition
    Default: "appmod"

  ContainerPort:
    Type: Number
    Description: The port number on the container that's bound to the user-specified or automatically assigned host port.
    Default: 80

  PortMappingsProtocol:
    Type: String
    Description: The protocol used for the port mapping.
    Default: HTTP

  ContainerDefinitionsPortMappingsHostPort:
    Type: String
    Description: The port number on the container instance to reserve for your container.

  Cpu:
    Type: Number
    Description: The number of cpu units reserved for the container.
    Default: 1024

  ExecutionRoleArn:
    Type: String
    Description: The Amazon Resource Name (ARN) of the task execution role that grants the Amazon ECS container agent permission to make AWS API calls on your behalf.
  
  Family:
    Type: String
    Description: The name of a family that this task definition is registered to.
    Default: "app1"

  Memory:
    Type: Number
    Description: The amount (in MiB) of memory used by the task.
    Default: 2048

  NetworkMode:
    Type: String
    Description: The Docker networking mode to use for the containers in the task.
    Default: awsvpc

  RequiresCompatibilities:
    Type: String
    Description: The task launch types the task definition was validated against.
    Default: ["FARGATE"]

  TaskRoleArn:
    Type: String
    Description: The short name or full Amazon Resource Name (ARN) of the AWS Identity and Access Management role that grants containers in the task permission to call AWS APIs on your behalf.

Resources:
  'ECSTaskDefinition':
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: !Ref ContainerDefinitionsImage
          LogConfiguration:
            LogDriver: !Ref LogConfigurationLogDriver
            Options:
              awslogs-group:  Fn::ImportValue: jd-preCWLogGroupName
              awslogs-region: !Ref awslogsregion
              awslogs-stream-prefix: !Sub ${ProductName}-${Environment}-${AppName}

          Name: !Ref TaskdefContainerName
          PortMappings:
          - ContainerPort: !Ref ContainerPort
            Protocol: !Ref PortMappingsProtocol
            HostPort: !Ref HostPort

          Environment:
          - Name: JAVA_OPTS
            Value: 'JAVA_OPTS'

      Cpu: !Ref Cpu
      # ExecutionRoleArn: !Ref ExecutionRoleArn
      Family: !Ref Family
      Memory: !Ref Memory
      NetworkMode: !Ref NetworkMode
      RequiresCompatibilities:
      - !Ref RequiresCompatibilities
      # Tags:
      # - Key: component
      #   Value: !Ref component
      # - Key: Name2
      #   Value: !Ref Name2
      # TaskRoleArn: !Ref TaskRoleArn
      Volumes:
      - Name: shared-efs-volume
                      